version: '3.8'
services:
  mongodb:
    image: 'mongo'
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - db:/var/lib/mongodb

  api:
    build: src
    restart: always
    ports:
      - '${EXPRESS_PORT}:${EXPRESS_PORT}'
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - DB_HOST=mongodb
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - EXPRESS_PORT=${EXPRESS_PORT}

volumes:
  db: