name: 'coverage'
on:
    pull_request:
        branches:
            - main
jobs:
    coverage:
        permissions:
            checks: write
            pull-requests: write
            contents: write
        runs-on: ubuntu-latest
        name: Coverage report
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                test-script: npm test
                working-directory: src/