name: Linter
on:
  pull_request:
        branches:
            - main
jobs:
  StandardJS:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install standard
        working-directory: ./src
        run: npm install -g standard
      - name: Standard Fix
        working-directory: ./src
        continue-on-error: true
        run: standard --fix --global it --global expect --global describe --global beforeAll --global afterEach --global beforeEach --global afterAll
      - name: Get Non fixable auto
        working-directory: ./src
        continue-on-error: true
        run: standard --global it --global expect --global describe --global beforeAll --global afterEach --global beforeEach --global afterAll > linter-nonfixable
      - name: Delete empty file linter-nonfixable
        working-directory: ./src
        run: |
          find linter-nonfixable -size 0 -delete
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "./src/linter-nonfixable"
      - name: Comment non fixable
        if: steps.check_files.outputs.files_exists == 'true'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Non fixable linter problems:
          filePath: ./src/linter-nonfixable
          comment-tag: linter-nonfixable
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[LINT] Applied linter fix"