name: Linter
on:
  pull_request:
        branches:
            - main
jobs:
  StandardJS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install standard
        working-directory: /src
      - run: standard --fix
        working-directory: /src